pipeline {
    agent any

    environment {
        CI = 'false'
        PATH = "${tool 'node18'}/bin:${env.PATH}" // Optional: If you configured NodeJS tool manually
    }

    stages {
        stage('Clone') {
            steps {
                git url: 'https://github.com/Avinash739jecrc/reactapprepo.git', branch: 'main'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                bat 'npm test -- --watchAll=false --passWithNoTests'
            }
        }

        stage('Build') {
            steps {
                bat 'npm run build'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Simulating deployment...'
                bat 'mkdir C:\\temp\\react-deploy'
                bat 'xcopy /E /I /Y build\\* C:\\temp\\react-deploy\\'
                echo 'Build deployed to C:\\temp\\react-deploy (fake prod)'
            }
        }
    }
}
